name: Publish PHP SDK

on:
  pull_request:
    branches:
      - master

jobs:
  setup_php:
    name: Setup PHP
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067 # 2.26.0
        with:
          php-version: '8.0'
          tools: composer
          extensions: ext-ffi

      - name: Composer check
        run: |
          composer install
          composer validate
        working-directory: languages/php/
